sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=eoepca/sysbox-pde
    - VERSION=0.5

before_script:
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build -f sysbox/Dockerfile --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${VERSION}"
deploy:
  provider: script
  script: 
    - docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${VERSION}"
  on:
    branch: master
