#!/bin/bash

# docker
sudo service docker start

sleep 5 

sudo chmod 777 /var/run/docker.sock

# theia
. "$NVM_DIR/nvm.sh"

cd /srv/theia

yarn start /workspace --hostname 0.0.0.0 --port 8889 & 

exec "$@"
