#!/bin/bash

# docker
JENKINS_HOME=/workspace/.jenkins

sudo service docker start

sleep 5 

sudo chmod 777 /var/run/docker.sock

# jenkins


JAVA_OPTS=-Djenkins.install.runSetupWizard=false

sudo /etc/init.d/jenkins start 

sleep 5 

sudo /etc/init.d/jenkins restart

sudo java -jar /tmp/jenkins-plugin-manager-*.jar --war /usr/share/jenkins/jenkins.war --plugin-download-directory ${JENKINS_HOME}/plugins/ --plugin-file /tmp/jenkins.plugins.txt

chown -R jenkins:jenkins .jenkins/

sudo /etc/init.d/jenkins restart 

# theia
. "$NVM_DIR/nvm.sh"

cd /srv/theia

#yarn start /workspace --hostname 0.0.0.0 --port 8889 & 

exec "$@"
