dependencies:
  - python=3.7
  - ipywidgets==7.5.1
  - jupyterlab==2.1.2
  - jupyterhub-singleuser==1.1.0
  - nbconvert==5.6.1
  - notebook==6.0.3
  - nteract_on_jupyter==2.1.3
  - widgetsnbextension 
  - ipyleaflet
  - nodejs
  - voila
  - nb_conda
  - conda-build
  - cwl-wrapper 
  - cwl2atom 
  - cwltool
  - jupyter-server-proxy
  - cookiecutter
  - s3cmd
  - awscli
  - pde-opensearch-client
  - stars-copy
  - pde-context
  - pip
  - pip:
    - awscli-plugin-endpoint
